# Generated by Django 3.0.7 on 2020-06-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full_link',
            field=models.CharField(max_length=500, unique=True, verbose_name='Full link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=7, unique=True, verbose_name='Short link'),
        ),
    ]
